apiVersion: v1
kind: Service
metadata:
  name: zta-backend
  namespace: zta
spec:
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
    app: backend
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001 
      protocol: TCP