apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: zta
  labels:
    {{- include "admin.labels" . | nindent 4 }}
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "admin.selectorLabels" . | nindent 6 }}
      app: admin
  template:
    metadata:
      labels:
        {{- include "admin.labels" . | nindent 8 }}
        app: admin
    spec:
      containers:
        - name: admin
          image: disciklean/zta-app-admin:latest
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP