apiVersion: v1
kind: Service
metadata:
  name: zta-admin
  namespace: zta
spec:
  selector:
    {{- include "admin.selectorLabels" . | nindent 4 }}
    app: admin
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001 
      protocol: TCP