apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: zta
  labels:
    {{- include "user.labels" . | nindent 4 }}
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "user.selectorLabels" . | nindent 6 }}
      app: user
  template:
    metadata:
      labels:
        {{- include "user.labels" . | nindent 8 }}
        app: user
    spec:
      containers:
        - name: user
          image: disciklean/zta-app-user:latest
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP